//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int id { get; set; }
        public string student_regno { get; set; }
        public string student_name { get; set; }
        public string academic_session { get; set; }
        public string academic_term { get; set; }
        public string class_name { get; set; }
        public string class_abbrev { get; set; }
        public string class_group { get; set; }
        public string subject_name { get; set; }
        public int student_mark { get; set; }
        public string category { get; set; }
    }
}
